### ISSUE TITLE
left or right side logic ?

### ISSUE THREAD

**Issue by flatmax** [skarrmann/janus#1]
Hi there, I love your keyboard.

I'm trying to workout how the firmware knows whether the board is the left or right side board ?
I can't see it in any of the qmk files : https://github.com/qmk/qmk_firmware/tree/master/keyboards/janus

**Comment by skarrmann** [comment]
Hi @flatmax!

Thank you for your inquiry, and I'm happy you like Janus! It has been a while since I looked at the QMK firmware configuration.

I will take a look tomorrow evening and get back to you around then.

Regards,
Steve

**Comment by skarrmann** [comment]
The Janus QMK firmware configuration did not have way to detect handedness. So if you plug the USB cable into the left side, all is well. But if you plug the USB cable in the right side, the layout would be mirrored!

By the PCB's design, I do not believe there is a hardware way of detecting whether the left or right side is plugged in.

So to fix this limitation and allow plugging in either side of the keyboard, I just added support for [detecting handedness by EEPROM](https://docs.qmk.fm/features/split_keyboard#handedness-by-eeprom).

Here is the pull request in the QMK firmware repository: https://github.com/qmk/qmk_firmware/pull/24261

Please let me know if this solution addresses your issue!

**Comment by skarrmann** [comment]
I am closing this issue since the solution supports either left or right side logic in QMK.

Please let me know if you need any assistance, thank you!
